#Author Alexander Parij
png(file="plot3.png", width = 480, height = 480, units = "px"  )
big_data <-read.table('household_power_consumption.txt', sep=";", na.strings = "?",header = TRUE)
few_days <-subset(big_data,as.Date(Date, format="%d/%m/%Y")>="2007-02-01" & as.Date(Date, format="%d/%m/%Y")<="2007-02-02")
few_days['times'] <- paste(few_days$Date , few_days$Time)
plot(strptime(few_days$times, "%d/%m/%Y %H:%M:%OS"),few_days$Sub_metering_1, type="n",xlab="",ylab="Energy sub metering")
lines(strptime(few_days$times, "%d/%m/%Y %H:%M:%OS"),few_days$Sub_metering_1, type="l")
lines(strptime(few_days$times, "%d/%m/%Y %H:%M:%OS"),few_days$Sub_metering_2, type="l", col = "red")
lines(strptime(few_days$times, "%d/%m/%Y %H:%M:%OS"),few_days$Sub_metering_3, type="l", col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=c(1,1), col=c("black","red","blue") ) 
dev.off()
